# Generated by Django 6.0.7 on 2026-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lat_to',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lon_to',
        ),
        migrations.AlterField(
            model_name='order',
            name='address_from',
            field=models.CharField(max_length=255, verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_to',
            field=models.CharField(max_length=255, verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
    ]
