# Generated by Django 6.0.7 on 2026-07-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_tariff_alter_order_options_order_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_from',
            field=models.CharField(max_length=256, verbose_name='Откуда'),
        ),
    ]
